spring:
  application:
    name: recruitment
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  # config pagination start 1
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      post: 6379
  # Multipart config
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # Mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#config jwt
caochung:
  jwt:
    base64-secret: ${JWT_SECRET}
    # expiration 1h
    access-token-validity-in-second: 3600
    # expiration 7day
    refresh-token-validity-in-second: 604800

#cloudinary config
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}